// Número compuesto de 11 caracteres:

// Caracteres 1 y 2: Categoría del pastel
// MC = Milk cake: Pastel de tres leches -> Todos los productos de este documento son MC
// GM = Gourmet
// JL = Jelly -> Gelatinas, flanes y cremas
// PD = Panadería -> Pan y galletas
// ML = Misceláneos -> 

// Caracteres 3 y 4: Sabor 1 del pastel
// Caracteres 5 y 6: Sabor 2 del pastel
// 00: No aplica
// SB: Strawberry -> Fresa
// CP: Capuchino
// NZ: Nuez
// CR: Crema Pastelera
// FT: Frutas
// DZ: Durazno
// ZQ: Zarzamora con queso
// PO: Piñón

// Caracteres 7 y 8: Cantidad de rellenos:
// DF: Double fill -> Doble relleno
// SF: Single fill -> Un relleno

// Caractreres 9-11: Número de personas recomendado

// Caracteres 12 y 13: Variantes del pastel

const milk = {
    'MCSB00DF01001': {
        id: "MCSB00DF01001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 250,
    },
    'MCCPNZDF01001': {
        id: "MCCPNZDF01001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 250,
    },
    'MCCPCRDF01001': {
        id: "MCCPCRDF01001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 250,
    },
    'MCFT00DF01001': {
        id: "MCFT00DF01001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 250,
    },
    'MCZQ00DF01001': {
        id: "MCZQ00DF01001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 280,
    },
    'MCDZ00DF01001': {
        id: "MCDZ00DF01001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 250,
    },
    'MCPO00DF01001': {
        id: "MCPO00DF01001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 10,
        option: 1,
        picture: [null],
        price: 500,
    },


    // 20 personas
    'MCSB00DF02001': {
        id: "MCSB00DF02001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 400,
    },
    'MCCPNZDF02001': {
        id: "MCCPNZDF02001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 400,
    },
    'MCCPCRDF02001': {
        id: "MCCPCRDF02001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 400,
    },
    'MCFT00DF02001': {
        id: "MCFT00DF02001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 400,
    },
    'MCZQ00DF02001': {
        id: "MCZQ00DF02001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 450,
    },
    'MCDZ00DF02001': {
        id: "MCDZ00DF02001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 400,
    },
    'MCPO00DF02001': {
        id: "MCPO00DF02001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 20,
        option: 1,
        picture: [null],
        price: 800,
    },

    
    // 30 personas
    'MCSB00DF03001': {
        id: "MCSB00DF03001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 600,
    },
    'MCCPNZDF03001': {
        id: "MCCPNZDF03001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 600,
    },
    'MCCPCRDF03001': {
        id: "MCCPCRDF03001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 600,
    },
    'MCFT00DF03001': {
        id: "MCFT00DF03001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 600,
    },
    'MCZQ00DF03001': {
        id: "MCZQ00DF03001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 670,
    },
    'MCDZ00DF03001': {
        id: "MCDZ00DF03001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 600,
    },
    'MCPO00DF03001': {
        id: "MCPO00DF03001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 30,
        option: 1,
        picture: [null],
        price: 1200,
    },


    // 50 personas
    'MCSB00DF05001': {
        id: "MCSB00DF05001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1200,
    },
    'MCCPNZDF05001': {
        id: "MCCPNZDF05001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1200,
    },
    'MCCPCRDF05001': {
        id: "MCCPCRDF05001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1200,
    },
    'MCFT00DF05001': {
        id: "MCFT00DF05001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1200,
    },
    'MCZQ00DF05001': {
        id: "MCZQ00DF05001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1380,
    },
    'MCDZ00DF05001': {
        id: "MCDZ00DF05001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 1200,
    },
    'MCPO00DF05001': {
        id: "MCPO00DF05001",
        name: "Pastel de tres leches de piñón",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 50,
        option: 1,
        picture: [null],
        price: 2400,
    },



        // 80 personas
        'MCSB00DF08001': {
            id: "MCSB00DF08001",
            name: "Pastel de tres leches de fresa",
            flavor1: "fresa",
            flavor2: null,
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 1920,
        },
        'MCCPNZDF08001': {
            id: "MCCPNZDF08001",
            name: "Pastel de tres leches de capuchino con nuez",
            flavor1: "capuchino",
            flavor2: "nuez",
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 1920,
        },
        'MCCPCRDF08001': {
            id: "MCCPCRDF08001",
            name: "Pastel de tres leches de capuchino con crema pastelera",
            flavor1: "capuchino",
            flavor2: "crema pastelera",
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 1920,
        },
        'MCFT00DF08001': {
            id: "MCFT00DF08001",
            name: "Pastel de tres leches de frutas",
            flavor1: "frutas",
            flavor2: null,
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 1920,
        },
        'MCZQ00DF08001': {
            id: "MCZQ00DF08001",
            name: "Pastel de tres leches de zarzamora con queso",
            flavor1: "zarzamora con queso",
            flavor2: null,
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 2200,
        },
        'MCDZ00DF08001': {
            id: "MCDZ00DF08001",
            name: "Pastel de tres leches de durazno",
            flavor1: "durazno",
            flavor2: null,
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 1920,
        },
        'MCPO00DF08001': {
            id: "MCPO00DF08001",
            name: "Pastel de tres leches de piñón",
            flavor1: "pinon",
            flavor2: null,
            fill: "double",
            persons: 80,
            option: 1,
            picture: [null],
            price: 3840,
        },



    // 100 personas
    'MCSB00DF10001': {
        id: "MCSB00DF10001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2400,
    },
    'MCCPNZDF10001': {
        id: "MCCPNZDF10001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2400,
    },
    'MCCPCRDF10001': {
        id: "MCCPCRDF10001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2400,
    },
    'MCFT00DF10001': {
        id: "MCFT00DF10001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2400,
    },
    'MCZQ00DF10001': {
        id: "MCZQ00DF10001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2750,
    },
    'MCDZ00DF10001': {
        id: "MCDZ00DF10001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 2400,
    },
    'MCPO00DF10001': {
        id: "MCPO00DF10001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 100,
        option: 1,
        picture: [null],
        price: 4800,
    },



    // 120 personas
    'MCSB00DF12001': {
        id: "MCSB00DF12001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 2880,
    },
    'MCCPNZDF12001': {
        id: "MCCPNZDF12001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 2880,
    },
    'MCCPCRDF12001': {
        id: "MCCPCRDF12001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 2880,
    },
    'MCFT00DF12001': {
        id: "MCFT00DF12001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 2880,
    },
    'MCZQ00DF12001': {
        id: "MCZQ00DF12001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 3300,
    },
    'MCDZ00DF12001': {
        id: "MCDZ00DF12001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 2880,
    },
    'MCPO00DF12001': {
        id: "MCPO00DF12001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 120,
        option: 1,
        picture: [null],
        price: 5760,
    },



    // 150 personas
    'MCSB00DF15001': {
        id: "MCSB00DF15001",
        name: "Pastel de tres leches de fresa",
        flavor1: "fresa",
        flavor2: null,
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 3600,
    },
    'MCCPNZDF15001': {
        id: "MCCPNZDF15001",
        name: "Pastel de tres leches de capuchino con nuez",
        flavor1: "capuchino",
        flavor2: "nuez",
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 3600,
    },
    'MCCPCRDF15001': {
        id: "MCCPCRDF15001",
        name: "Pastel de tres leches de capuchino con crema pastelera",
        flavor1: "capuchino",
        flavor2: "crema pastelera",
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 3600,
    },
    'MCFT00DF15001': {
        id: "MCFT00DF15001",
        name: "Pastel de tres leches de frutas",
        flavor1: "frutas",
        flavor2: null,
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 3600,
    },
    'MCZQ00DF15001': {
        id: "MCZQ00DF15001",
        name: "Pastel de tres leches de zarzamora con queso",
        flavor1: "zarzamora con queso",
        flavor2: null,
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 4125,
    },
    'MCDZ00DF15001': {
        id: "MCDZ00DF15001",
        name: "Pastel de tres leches de durazno",
        flavor1: "durazno",
        flavor2: null,
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 3600,
    },
    'MCPO00DF15001': {
        id: "MCPO00DF15001",
        name: "Pastel de tres leches de piñón",
        flavor1: "pinon",
        flavor2: null,
        fill: "double",
        persons: 150,
        option: 1,
        picture: [null],
        price: 7200,
    },
}

export default milk;